{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "6e990b78_f947323a",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 13,
      "author": {
        "id": 97483
      },
      "writtenOn": "2022-03-20T16:49:10Z",
      "side": 1,
      "message": "Well, only the IOException is managed. Any unchecked exception would be swallowed instead, which isn\u0027t desirable.",
      "range": {
        "startLine": 13,
        "startChar": 11,
        "endLine": 13,
        "endChar": 49
      },
      "revId": "80e999641ae4a5a8b714c8ec039efd8e6a401de2",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f948cc02_bae218c6",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 13,
      "author": {
        "id": 241433
      },
      "writtenOn": "2022-03-21T09:07:56Z",
      "side": 1,
      "message": "IOException is the only exception that can be raised in the finally block and could override the exception in the try block. The rest of the exceptions will just be wrapped in a TransportException.",
      "parentUuid": "6e990b78_f947323a",
      "range": {
        "startLine": 13,
        "startChar": 11,
        "endLine": 13,
        "endChar": 49
      },
      "revId": "80e999641ae4a5a8b714c8ec039efd8e6a401de2",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f99a0d85_5fd31e97",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 13,
      "author": {
        "id": 97483
      },
      "writtenOn": "2022-04-21T07:58:08Z",
      "side": 1,
      "message": "What about the unchecked exceptions instead?",
      "parentUuid": "f948cc02_bae218c6",
      "range": {
        "startLine": 13,
        "startChar": 11,
        "endLine": 13,
        "endChar": 49
      },
      "revId": "80e999641ae4a5a8b714c8ec039efd8e6a401de2",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c5cbb7a3_d219503f",
        "filename": "/COMMIT_MSG",
        "patchSetId": 4
      },
      "lineNbr": 13,
      "author": {
        "id": 4
      },
      "writtenOn": "2022-05-21T08:59:14Z",
      "side": 1,
      "message": "@Luca: Where exactly do you think an unchecked exception is swallowed or suppressed in #downloadPackedObject ?\n\nAFAICS the only place in this method where a checked exception is thrown in a finally block is in line 539. This only happens if deleting the index file in line 534 fails with an IOException. Though e1, which would be suppressed, is added to e via #addSuppressed which is wrapped into the new TransportException.",
      "parentUuid": "f99a0d85_5fd31e97",
      "range": {
        "startLine": 13,
        "startChar": 11,
        "endLine": 13,
        "endChar": 49
      },
      "revId": "80e999641ae4a5a8b714c8ec039efd8e6a401de2",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31"
    }
  ]
}