{
  "comments": [
    {
      "key": {
        "uuid": "436ae1f2_ab82cd37",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 10,
      "author": {
        "id": 44628
      },
      "writtenOn": "2019-09-02T11:59:00Z",
      "side": 1,
      "message": "That\u0027s exactly what I was observing in bug 548716.",
      "range": {
        "startLine": 10,
        "startChar": 12,
        "endLine": 10,
        "endChar": 20
      },
      "revId": "c79aed0f5115d9b78fe380e6ab456f173e45b588",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "93b5b68d_58e79355",
        "filename": "/COMMIT_MSG",
        "patchSetId": 3
      },
      "lineNbr": 23,
      "author": {
        "id": 44628
      },
      "writtenOn": "2019-09-02T11:59:00Z",
      "side": 1,
      "message": "Which explains why the next fetch would re-want them, and then fail in its BatchRefUpdate and raise this misleading \"lock failed\" exception.",
      "range": {
        "startLine": 22,
        "startChar": 20,
        "endLine": 23,
        "endChar": 38
      },
      "revId": "c79aed0f5115d9b78fe380e6ab456f173e45b588",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "105327f4_eec90dba",
        "filename": "org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/PackedBatchRefUpdate.java",
        "patchSetId": 3
      },
      "lineNbr": 396,
      "author": {
        "id": 44628
      },
      "writtenOn": "2019-09-02T11:51:07Z",
      "side": 1,
      "message": "Which lock failed? Perhaps a different exception would be better.",
      "revId": "c79aed0f5115d9b78fe380e6ab456f173e45b588",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "19caa00a_7dbf10a0",
        "filename": "org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/PackedBatchRefUpdate.java",
        "patchSetId": 3
      },
      "lineNbr": 396,
      "author": {
        "id": 98905
      },
      "writtenOn": "2019-09-02T12:18:06Z",
      "side": 1,
      "message": "see below.",
      "parentUuid": "105327f4_eec90dba",
      "revId": "c79aed0f5115d9b78fe380e6ab456f173e45b588",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "3073f608_6c115692",
        "filename": "org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/PackedBatchRefUpdate.java",
        "patchSetId": 3
      },
      "lineNbr": 404,
      "author": {
        "id": 44628
      },
      "writtenOn": "2019-09-02T11:51:07Z",
      "side": 1,
      "message": "Please don\u0027t report a lock failure here. That\u0027s what happens in bug 548716, but it\u0027s not correct. Rather the fetch requests a ref it already had.",
      "range": {
        "startLine": 404,
        "startChar": 5,
        "endLine": 404,
        "endChar": 32
      },
      "revId": "c79aed0f5115d9b78fe380e6ab456f173e45b588",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "d409c38c_2067358c",
        "filename": "org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/file/PackedBatchRefUpdate.java",
        "patchSetId": 3
      },
      "lineNbr": 404,
      "author": {
        "id": 98905
      },
      "writtenOn": "2019-09-02T12:18:06Z",
      "side": 1,
      "message": "I think this is a lock failure from the perspective of a BatchRefUpdate: the update tries to apply an update that corresponds to an older state.",
      "parentUuid": "3073f608_6c115692",
      "range": {
        "startLine": 404,
        "startChar": 5,
        "endLine": 404,
        "endChar": 32
      },
      "revId": "c79aed0f5115d9b78fe380e6ab456f173e45b588",
      "serverId": "97ee7c02-f12f-4043-b43e-dea463d88b31",
      "unresolved": false
    }
  ]
}